<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KULANDASAMYC" name="PushToProd_3.A_PushToProd" tests="5" failures="0" timestamp="17 Jul 2019 07:32:41 GMT" time="41.562" errors="1">
  <testcase name="B_HousingTransfer" time="21.183" classname="PushToProd_3.A_PushToProd"/>
  <testcase name="AA_PushEverythingElse" time="0.018" classname="PushToProd_3.A_PushToProd">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at PushToProd_3.A_PushToProd.AA_PushEverythingElse(A_PushToProd.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- AA_PushEverythingElse -->
  <testcase name="A_LoginAndFocusShow" time="13.153" classname="PushToProd_3.A_PushToProd"/>
  <testcase name="C_PushConfirmationLettersToProduction" time="4.203" classname="PushToProd_3.A_PushToProd"/>
  <testcase name="D_PushWebFiles" time="3.005" classname="PushToProd_3.A_PushToProd"/>
</testsuite> <!-- PushToProd_3.A_PushToProd -->
