<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="KULANDASAMYC" name="Configure_Show.B_ConfigureStatuses" tests="15" failures="0" timestamp="6 Aug 2018 10:13:41 GMT" time="45.225" errors="2">
  <testcase name="D_DateStatus" time="4.108" classname="Configure_Show.B_ConfigureStatuses"/>
  <testcase name="E_ConfigureMembershipStatuses" time="0.001" classname="Configure_Show.B_ConfigureStatuses">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1
	at Configure_Show.B_ConfigureStatuses.E_ConfigureMembershipStatuses(B_ConfigureStatuses.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- E_ConfigureMembershipStatuses -->
  <testcase name="F_MembershipStatus" time="2.375" classname="Configure_Show.B_ConfigureStatuses"/>
  <testcase name="H_RegistrationStatus" time="2.430" classname="Configure_Show.B_ConfigureStatuses"/>
  <testcase name="D_DateStatus" time="2.568" classname="Configure_Show.B_ConfigureStatuses"/>
  <testcase name="G_ConfigureRegistrationStatuses" time="0.001" classname="Configure_Show.B_ConfigureStatuses">
    <error type="java.lang.ArrayIndexOutOfBoundsException" message="2">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 2
	at Configure_Show.B_ConfigureStatuses.G_ConfigureRegistrationStatuses(B_ConfigureStatuses.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- G_ConfigureRegistrationStatuses -->
  <testcase name="H_RegistrationStatus" time="2.169" classname="Configure_Show.B_ConfigureStatuses"/>
  <testcase name="I_TearDown" time="0.562" classname="Configure_Show.B_ConfigureStatuses"/>
  <testcase name="C_ConfigureDateStatuses" time="2.476" classname="Configure_Show.B_ConfigureStatuses"/>
  <testcase name="D_DateStatus" time="3.189" classname="Configure_Show.B_ConfigureStatuses"/>
  <testcase name="B_Status" time="1.960" classname="Configure_Show.B_ConfigureStatuses"/>
  <testcase name="H_RegistrationStatus" time="2.431" classname="Configure_Show.B_ConfigureStatuses"/>
  <testcase name="H_RegistrationStatus" time="2.136" classname="Configure_Show.B_ConfigureStatuses"/>
  <testcase name="A_LoginAndFocusShow" time="16.563" classname="Configure_Show.B_ConfigureStatuses"/>
  <testcase name="F_MembershipStatus" time="2.256" classname="Configure_Show.B_ConfigureStatuses"/>
</testsuite> <!-- Configure_Show.B_ConfigureStatuses -->
